version: '3'
services:
  postgres_db:
    image: postgres
  mongo_db:
    image: mongo
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
      - mongo_db
    command: sh "/app/docker/web/entrypoint.sh"
    # privileged: true
